import {
  RekognitionClient,
  CreateCollectionCommand,
  DetectLabelsCommand,
  IndexFacesCommand,
  SearchFacesByImageCommand,
} from '@aws-sdk/client-rekognition';
import { S3Client, GetObjectCommand } from '@aws-sdk/client-s3';
import { prisma } from '../config/database';
import { env } from '../config';
import sharp from 'sharp';

// Rekognition is not supported in all regions, so we hardcode to eu-west-1 (Ireland)
// which has full support.
const rekognitionClient = new RekognitionClient({
  region: 'eu-west-1',
  credentials: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID || '',
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || '',
  },
});

// S3 client uses the user's bucket region (eu-north-1)
const s3Client = new S3Client({
  region: process.env.AWS_REGION || 'eu-north-1',
  credentials: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID || '',
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || '',
  },
});

const COLLECTION_ID = 'antigravity-users';
const BUCKET_NAME = process.env.S3_BUCKET_NAME || 'hareesh-project-uploads';

export class RekognitionService {
  /**
   * Helper to fetch an image from S3 and convert to a Uint8Array buffer
   * This is required because Rekognition can only access S3 buckets in the SAME region.
   * Since the bucket is in eu-north-1 and Rekognition is in eu-west-1, we must pass the bytes directly.
   */
  private static async getImageBytesFromS3(s3Key: string): Promise<Uint8Array> {
    const command = new GetObjectCommand({
      Bucket: BUCKET_NAME,
      Key: s3Key,
    });
    const response = await s3Client.send(command);
    if (!response.Body) {
      throw new Error('S3 object body is empty');
    }
    const arrayBuffer = await response.Body.transformToByteArray();
    
    // Convert all images to JPEG using sharp to ensure compatibility with AWS Rekognition
    // Rekognition rejects WebP, HEIC, etc natively.
    const jpegBuffer = await sharp(Buffer.from(arrayBuffer))
      .jpeg({ quality: 90 })
      .toBuffer();
      
    return new Uint8Array(jpegBuffer);
  }

  /**
   * Initializes the global face collection.
   * This should be called once on server startup.
   */
  static async initializeCollection() {
    try {
      const command = new CreateCollectionCommand({ CollectionId: COLLECTION_ID });
      await rekognitionClient.send(command);
      console.log(`[Rekognition] Created new collection: ${COLLECTION_ID}`);
    } catch (error: any) {
      if (error.name === 'ResourceAlreadyExistsException') {
        console.log(`[Rekognition] Collection ${COLLECTION_ID} already exists.`);
      } else {
        console.error('[Rekognition] Failed to initialize collection:', error);
      }
    }
  }

  /**
   * Detects labels (objects, scenes, concepts) in an image.
   */
  static async detectLabels(s3Key: string): Promise<string[]> {
    try {
      const imageBytes = await this.getImageBytesFromS3(s3Key);
      const command = new DetectLabelsCommand({
        Image: {
          Bytes: imageBytes,
        },
        MaxLabels: 10,
        MinConfidence: 75,
      });

      const response = await rekognitionClient.send(command);
      
      const tags = response.Labels
        ?.map((label) => label.Name)
        .filter((name): name is string => !!name) || [];

      return tags;
    } catch (error) {
      console.error('[Rekognition] DetectLabels Error:', error);
      return [];
    }
  }

  /**
   * Indexes a user's selfie into the collection.
   * Returns the FaceId generated by AWS Rekognition.
   */
  static async indexUserFace(userId: string, s3Key: string): Promise<string | null> {
    try {
      const imageBytes = await this.getImageBytesFromS3(s3Key);
      const command = new IndexFacesCommand({
        CollectionId: COLLECTION_ID,
        Image: {
          Bytes: imageBytes,
        },
        ExternalImageId: userId,
        MaxFaces: 1, // Only index the largest face (assumed to be the selfie subject)
        QualityFilter: 'AUTO',
        DetectionAttributes: ['ALL'],
      });

      const response = await rekognitionClient.send(command);

      if (response.FaceRecords && response.FaceRecords.length > 0) {
        const faceId = response.FaceRecords[0].Face?.FaceId;
        return faceId || null;
      }
      
      return null;
    } catch (error) {
      console.error('[Rekognition] IndexUserFace Error:', error);
      return null;
    }
  }

  /**
   * Searches an uploaded event photo for ANY registered faces.
   */
  static async searchFacesInImage(s3Key: string) {
    try {
      const imageBytes = await this.getImageBytesFromS3(s3Key);
      const command = new SearchFacesByImageCommand({
        CollectionId: COLLECTION_ID,
        Image: {
          Bytes: imageBytes,
        },
        MaxFaces: 5,
        FaceMatchThreshold: 85,
      });

      const response = await rekognitionClient.send(command);

      const matches = response.FaceMatches?.map((match) => {
        return {
          faceId: match.Face?.FaceId,
          confidence: match.Similarity,
          externalImageId: match.Face?.ExternalImageId, // This is our User ID
          boundingBox: match.Face?.BoundingBox,
        };
      }) || [];

      return matches;
    } catch (error: any) {
      // If no faces are found in the image, it throws InvalidParameterException
      if (error.name === 'InvalidParameterException' || error.message?.includes('There are no faces in the image')) {
        return [];
      }
      console.error('[Rekognition] SearchFacesByImage Error:', error);
      return [];
    }
  }
}
